# 
# worlds:
# 
# earth-world-name: default: world 
# The name of your world that is earth.
# This should be the name main world where people work on stuff and make bases.
# 
# mobs:
# 
# tick-interval: default: 2 range: 1-20
# How often aliens tick in Minecraft ticks, there are 20 ticks in 1 second
# 
# max-per-player: default: 12 range: 1-64
# maximum number of aliens per player per world
# 
# 
worlds:
  earth-name: world
aliens:
  tick-interval: 2
  max-per-player: 8
