# Enable this to get bug fixes and support asap
auto-update: true

worlds:

  # The name of your world that is Earth.
  # This should be the name main world where people work on stuff and make bases.
  earth-name: world

  # If set to true, players can use Nether portals in Galactifun planet worlds.
  allow-nether-portals: false

aliens:

  # How often aliens tick in Minecraft ticks - there are 20 ticks in 1 second
  tick-interval: 2

  # Maximum number of aliens per player per world
  max-per-player: 8

  # Chance for a Leech to eat an item
  leech-eat-chance: 50

rockets:
  
  # Messages while rocket is launching. Must have at least 4
  launch-msgs: 
    - Forgetting parachutes
    - Restocking snack bin
    - Aligning planets
    - Igniting sun
    - Inventing funny launch messages
    - Thanking TheBusyBiscuit
    - Faking Moon landings
    - Taking one small step
    - Going Boomer
    - Not going home

other:

  # The range that the automatic door checks for players
  auto-door-range: 2

  # Blocks prohibited to be used by the automatic door
  auto-door-banned-types:
    - BEDROCK
    - CAKE
    - BARRIER
    - COMMAND_BLOCK
    - END_PORTAL
    - STRUCTURE_BLOCK

  # Max range for sealed command. High values may impact performance, low values may miss sealed areas.
  # More info: https://github.com/Slimefun-Addon-Community/Galactifun/wiki/Sealing#Range
  sealed-command-max-range: 300000
